server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: https://eventservice-alpha-2026.azurewebsites.net
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1

        - id: bienestar-service
          uri: https://bienestarservice-alpha-2026.azurewebsites.net
          predicates:
            - Path=/api/bienestar/**
          filters:
            - StripPrefix=1

        - id: gamification-service
          uri: https://gamification-service.icysea-59b45732.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/gamification/**
          filters:
            - StripPrefix=1

        - id: estadisticas-service
          uri: https://estadisticas-eci.icysea-59b45732.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/estadisticas/**
          filters:
            - StripPrefix=1

        - id: profile-service
          uri: https://alphaeci-profile-service-prod.icycoast-fc5305af.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/v1/users/**

        - id: matching-service-matches
          uri: https://alphaeci-matching-service-prod.icycoast-fc5305af.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/v1/matches/**

        - id: matching-service-categories
          uri: https://alphaeci-matching-service-prod.icycoast-fc5305af.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/v1/categories/**

        - id: identity-service
          uri: https://alphaeci-identity-service-prod.icycoast-fc5305af.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/v1/auth/**

        - id: parches-service
          uri: https://alpha-eci-parches-prod.azurewebsites.net/
          predicates:
            - Path=/api/v1/parches/**

        - id: notification-service
          uri: https://notification-service-prod.gentlebeach-15ecf803.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/notifications/**

        - id: chat-service
          uri: https://chat-service-prod.gentlebeach-15ecf803.eastus.azurecontainerapps.io
          predicates:
            - Path=/api/chat/**